# Generated by Django 6.0.7 on 2026-07-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='ACTIVE', max_length=20),
        ),
    ]
