# Generated by Django 6.0.7 on 2026-07-26 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancehistory',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interventions.intervention'),
        ),
    ]
